language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=allegro
    - LISP=abcl
    - LISP=ecl
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=ecl
    - env: LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/fukamachi/roswell/fix-install-script/scripts/install-for-ci.sh | sh

before_script:
  - ros --version
  - ros config

script:
  - ros -s prove -s uiop -e '(or (prove:run :sxql-test) (uiop:quit -1))'
