language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=allegro
    - LISP=abcl
    - LISP=ecl
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=ecl
    - env: LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh
  - ros install prove

before_script:
  - ros --version
  - ros config

script:
  - run-prove sxql-test.asd
